# Generated by Django 6.0.6 on 2026-06-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
