# Generated by Django 6.0.6 on 2026-07-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_books_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authors',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
