# Generated by Django 6.0.6 on 2026-06-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_authors_biography_authors_email_authors_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
